AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-13

  Sample SAM Template for sam-app-13

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.9
      CodeUri: hello_world/
      Handler: app.lambda_handler
      MemorySize: 128
      Timeout: 300

  MySQSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: MySQSQueue

  MySQSEventSourceMapping:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 3
      Enabled: true
      EventSourceArn: !GetAtt MySQSQueue.Arn
      FunctionName: !Ref MyLambdaFunction
      MaximumBatchingWindowInSeconds: 120
      ParallelizationFactor: 10
