AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-13

  Sample SAM Template for sam-app-13

Resources:
  MySQSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: sam-app-13-queue9
      VisibilityTimeout: 300

  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.9
      CodeUri: hello_world/
      Handler: app.lambda_handler
      MemorySize: 128
      Timeout: 30

  MySQSEventSourceMapping:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 3
      EventSourceArn: !GetAtt MySQSQueue.Arn
      FunctionName: !GetAtt MyLambdaFunction.Arn
      MaximumBatchingWindowInSeconds: 120
